# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views\Exportr_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExporterView(object):
    def setupUi(self, ExporterView):
        ExporterView.setObjectName("ExporterView")
        ExporterView.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ExporterView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectFilesButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFilesButton.setObjectName("selectFilesButton")
        self.verticalLayout.addWidget(self.selectFilesButton)
        self.filesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.filesListWidget.setObjectName("filesListWidget")
        self.verticalLayout.addWidget(self.filesListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.netcdfCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.netcdfCheckBox.setChecked(True)
        self.netcdfCheckBox.setObjectName("netcdfCheckBox")
        self.verticalLayout_2.addWidget(self.netcdfCheckBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout_3.addWidget(self.exportButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.revLabel = QtWidgets.QLabel(self.centralwidget)
        self.revLabel.setText("")
        self.revLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.revLabel.setObjectName("revLabel")
        self.gridLayout.addWidget(self.revLabel, 1, 0, 1, 1)
        self.darkCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.darkCheckBox.setObjectName("darkCheckBox")
        self.gridLayout.addWidget(self.darkCheckBox, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        ExporterView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ExporterView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ExporterView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ExporterView)
        self.statusbar.setObjectName("statusbar")
        ExporterView.setStatusBar(self.statusbar)

        self.retranslateUi(ExporterView)
        QtCore.QMetaObject.connectSlotsByName(ExporterView)

    def retranslateUi(self, ExporterView):
        _translate = QtCore.QCoreApplication.translate
        ExporterView.setWindowTitle(_translate("ExporterView", "MainWindow"))
        self.selectFilesButton.setText(_translate("ExporterView", "Select Files"))
        self.netcdfCheckBox.setText(_translate("ExporterView", "netCDF"))
        self.exportButton.setText(_translate("ExporterView", "Begin Export"))
        self.darkCheckBox.setText(_translate("ExporterView", "Dark Theme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExporterView = QtWidgets.QMainWindow()
    ui = Ui_ExporterView()
    ui.setupUi(ExporterView)
    ExporterView.show()
    sys.exit(app.exec_())
