# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views\Exportr_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExporterView(object):
    def setupUi(self, ExporterView):
        ExporterView.setObjectName("ExporterView")
        ExporterView.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ExporterView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectFilesButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectFilesButton.setFont(font)
        self.selectFilesButton.setObjectName("selectFilesButton")
        self.verticalLayout.addWidget(self.selectFilesButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.fileAnalyzeProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.fileAnalyzeProgressBar.setProperty("value", 24)
        self.fileAnalyzeProgressBar.setObjectName("fileAnalyzeProgressBar")
        self.horizontalLayout_2.addWidget(self.fileAnalyzeProgressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.fileScanLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileScanLabel.setText("")
        self.fileScanLabel.setObjectName("fileScanLabel")
        self.verticalLayout.addWidget(self.fileScanLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.scanFilesProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.scanFilesProgressBar.setProperty("value", 24)
        self.scanFilesProgressBar.setObjectName("scanFilesProgressBar")
        self.horizontalLayout_3.addWidget(self.scanFilesProgressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.filesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.filesListWidget.setObjectName("filesListWidget")
        self.verticalLayout.addWidget(self.filesListWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.netcdfCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.netcdfCheckBox.setChecked(True)
        self.netcdfCheckBox.setObjectName("netcdfCheckBox")
        self.horizontalLayout_5.addWidget(self.netcdfCheckBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.exportButton.setFont(font)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.revLabel = QtWidgets.QLabel(self.centralwidget)
        self.revLabel.setText("")
        self.revLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.revLabel.setObjectName("revLabel")
        self.gridLayout.addWidget(self.revLabel, 1, 0, 1, 1)
        self.darkCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.darkCheckBox.setObjectName("darkCheckBox")
        self.gridLayout.addWidget(self.darkCheckBox, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        ExporterView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ExporterView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ExporterView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ExporterView)
        self.statusbar.setObjectName("statusbar")
        ExporterView.setStatusBar(self.statusbar)

        self.retranslateUi(ExporterView)
        QtCore.QMetaObject.connectSlotsByName(ExporterView)

    def retranslateUi(self, ExporterView):
        _translate = QtCore.QCoreApplication.translate
        ExporterView.setWindowTitle(_translate("ExporterView", "MainWindow"))
        self.selectFilesButton.setText(_translate("ExporterView", "Select Files"))
        self.label.setText(_translate("ExporterView", "File Analyze Progress"))
        self.label_2.setText(_translate("ExporterView", "Scanning Progress    "))
        self.groupBox.setTitle(_translate("ExporterView", "Export Formats"))
        self.netcdfCheckBox.setText(_translate("ExporterView", "netCDF"))
        self.exportButton.setText(_translate("ExporterView", "Begin Export"))
        self.darkCheckBox.setText(_translate("ExporterView", "Dark Theme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExporterView = QtWidgets.QMainWindow()
    ui = Ui_ExporterView()
    ui.setupUi(ExporterView)
    ExporterView.show()
    sys.exit(app.exec_())
